// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcptockfqhwceaeevhzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjcHRvY2tmcWh3Y2VhZWV2aHpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTQ0MzAsImV4cCI6MjA3MzI3MDQzMH0.CgM2ggVrU55JKV-Sretipve5JFJKn5PitS9-jvGw6s4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});